import Head from "next/head"
import BridgeCard from "@/components/BridgeCard"
import LiquidityCard from "@/components/LiquidityCard"

const Home = () => {
  return (
    <div>
      <Head>
        <title>Scroll Bridge</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <div className="flex flex-col items-center justify-center min-h-screen">
        <Head>
          <title>Degenmate Scroll Bridge</title>
        </Head>

        <div className="flex flex-col items-center justify-center w-full gap-10 mt-20 mb-20">
          <BridgeCard />
          <LiquidityCard />
        </div>
      </div>
    </div>
  )
}

export default Home
