import Head from "next/head"
import BridgeCard from "@/components/BridgeCard"

const Home = () => {
  return (
    <div >
      <Head>
        <title>Scroll Bridge</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <div className="flex flex-col items-center justify-center min-h-screen">
        <Head>
          <title>Degenmate Scroll Bridge</title>
        </Head>

        <BridgeCard />
      </div>
    </div>
  )
}

export default Home
